### ISSUE TITLE
Non latin characters not being correctly displayed

### ISSUE THREAD

**Issue by anrodon** [anrodon/nem-microwallet#1]
Discovered by @mizunashi_6393 on Medium:

![](https://preview.ibb.co/bVPrEa/Screen_Shot_2017_07_17_at_19_20_08.png)

Has been reproduced by simply sending a message including non latin characters using the NEM Nanowallet and displaying the transaction with the Microwallet, getting in wrong displayings due to what seems to be encoding errors.

**Comment by mizunashi** [comment]
Thanks!
